CREATE TABLE EMPLOYEE(
 SSN INT PRIMARY KEY , 
 BDate DATE , 
 HomeADDRESS VARCHAR(20),
 SEX VARCHAR(1), 
 SALARY INT,
 SUPERSSN INT FOREIGN KEY REFERENCES EMPLOYEE(SSN),
 FNAME VARCHAR(20),
 LNAME VARCHAR(20),
 MINIT INT
);

ALTER TABLE EMPLOYEE
ADD  DNO INT ;

ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNumber);

CREATE TABLE DEPARTMENT
(
 DNAME VARCHAR(20) , 
 DNumber int PRIMARY KEY,
 MGRSSN INT FOREIGN KEY REFERENCES EMPLOYEE(SSN),
 MGRSTARTDATE DATE
);


CREATE TABLE DEPT_Location
(
    DNUMBER INT NOT NULL FOREIGN KEY REFERENCES DEPARTMENT(DNumber) ,
    DLOCATION VARCHAR(20) NOT NULL
    CONSTRAINT PK_UserGroup PRIMARY KEY NONCLUSTERED (DNUMBER,DLOCATION)
);

CREATE TABLE PROJECT 
(
    PNAME VARCHAR(20), 
    PNUMBER INT PRIMARY KEY,
    PLOCATION VARCHAR(20),
    DNUM INT FOREIGN KEY REFERENCES DEPARTMENT(DNumber)
);



CREATE TABLE WORK(
    HOURS INT,
    ESSIN  INT FOREIGN KEY REFERENCES EMPLOYEE(SSN),
    PNO INT FOREIGN KEY REFERENCES PROJECT(PNUMBER),
    CONSTRAINT PK_WORKGroup PRIMARY KEY NONCLUSTERED (PNO,ESSIN)
);

CREATE TABLE DEPENDENTs(
     ESSIN  INT FOREIGN KEY REFERENCES EMPLOYEE(SSN),
     DEPARTMENT_NAME VARCHAR(20)
     CONSTRAINT PK_UserGroup1 PRIMARY KEY NONCLUSTERED (ESSIN,DEPARTMENT_NAME),
     SEX VARCHAR(1),
     BDATE DATE,
     RELATIONSHIP INT
);